import type { MetadataRoute } from 'next'
import { absoluteUrl } from '@/lib/site-url'

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date()

  const marketingPages = [
    '/',
    '/pricing',
    '/pricing/free-inventory-software',
    '/demo',
    '/features',
    '/features/barcode-scanning',
    '/features/offline-mobile-scanning',
    '/features/check-in-check-out',
    '/features/bulk-editing',
    '/features/low-stock-alerts',
    '/solutions',
    '/solutions/warehouse-inventory',
    '/solutions/ecommerce-inventory',
    '/solutions/construction-tools',
    '/solutions/small-business',
    '/solutions/mobile-inventory-app',
    '/solutions/asset-tracking',
    '/compare',
    '/compare/sortly-alternative',
    '/compare/boxhero-alternative',
    '/compare/fishbowl-alternative',
    '/compare/inflow-alternative',
    '/migration',
    '/migration/sortly',
    '/integrations',
    '/security',
    '/learn',
    '/learn/guide',
    '/learn/guide/cycle-counting',
    '/learn/guide/qr-codes-for-inventory',
    '/learn/guide/how-to-set-up-barcode-system',
    '/learn/guide/how-to-set-reorder-points',
    '/learn/guide/perpetual-vs-periodic-inventory',
    '/learn/blog',
    '/learn/blog/inventory-management-platforms-for-ecommerce-2025',
    '/learn/glossary',
    '/learn/glossary/80-20-inventory-rule',
    '/learn/glossary/barcodes-vs-qr-codes',
    '/learn/glossary/consignment-inventory',
    '/learn/glossary/cost-of-goods-sold',
    '/learn/glossary/economic-order-quantity',
    '/learn/glossary/fifo-vs-lifo',
    '/learn/glossary/inventory-turnover',
    '/learn/glossary/inventory-vs-stock',
    '/learn/glossary/lot-number-vs-serial-number',
    '/learn/glossary/markup-vs-margin',
    '/learn/glossary/types-of-inventory',
    '/learn/glossary/wholesaler-vs-distributor',
    '/learn/tools',
    '/learn/tools/markup-margin-calculator',
    '/learn/tools/reorder-point-calculator',
    '/learn/templates',
    '/learn/templates/inventory-spreadsheet',
    '/learn/templates/cycle-count-sheet',
    '/privacy',
    '/terms',
  ]

  return marketingPages.map((pathname) => ({
    url: absoluteUrl(pathname),
    lastModified,
  }))
}
